# start by pulling the python image
FROM python:3.10-alpine

# copy the requirements file into the image
COPY ./requirements-test.txt /app/requirements-test.txt

# switch working directory
WORKDIR /app

# install the dependencies and packages in the requirements file
RUN pip install -r requirements-test.txt

# copy every content from the local file to the image
COPY . /app

EXPOSE 8080

CMD ["bash"]