# Workflow to run tests using docker containers

name: CI Tests
on:
    push:
        branches:
        - main
    pull_request:
        branches:
        - '**'

jobs:
    run_tests:
        name: Run tests
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
              name: Checkout
            - name: Run tests
              run: |
                docker-compose up --build test

          
    